\subsection{@name@}
    \begin{multicols}{2}
    \textit{
        @itemdescription@
    }
    \columnbreak
    \includegraphics{../art/\subtitle/anomalies/@name@}
    \end{multicols}
    \textit{
        @itemdescription@
    }
\\%
